version: '3'
services:
  dev:
    #image: mcr.microsoft.com/devcontainers/python:0-3.11
    build: dev
    user: "vscode:vscode"
    depends_on:
      - web
    volumes:
      - odoo-dev-code:/workspace
      - odoo-dev-cache:/home/vscode/.cache
     # - ~/.ssh:/home/vscode/.ssh # ssh key
      - ..:/repo
    environment:
      - db_host=mydb
      - db_password=myodoo
      - db_user=odoo
    command: /bin/sh -c "while sleep 1000; do :; done"  
    # Runs app on the same network as the service container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:web
  web:
    build: web
    depends_on:
      - mydb
    ports:
      - "8089:8069"
      - "8889:8888"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./web/config:/etc/odoo
      - odoo-dev-code:/src
     
    environment:
      - db_host=mydb
      - db_password=myodoo
      - db_user=odoo
  mydb:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-dev-cache:
  odoo-dev-code:
  odoo-web-data:
  odoo-db-data:
  